all: produit_scalaire

produit_scalaire: produit_scalaire.c
		gcc -c produit_scalaire.c -o produit_scalaire.o
		gcc produit_scalaire.o -o produit_scalaire

clean:
		rm -f produit_scalaire 
		rm -f produit_scalaire.o 